### ISSUE TITLE
is it possible to remove backdrop?

### ISSUE THREAD

**Issue by ghiscoding** [mpalourdio/ng-http-loader#110]
I've been spending some time trying to find if it's possible to remove the backdrop entirely. Basically, I still want the user to be able to click on buttons and such in the App but this spinner (spinKit) seems to always use a backdrop. 

Considering that I resize the spinner with this
```css
#spinner {
  opacity: .4 !important;
}
.sk-double-bounce {
  width: 50px !important;
  height: 50px !important;
}
```
how can I make the spinner show, which I don't mind if it's not clickable in that area, and be able to click elsewhere. 

Is it even possible to remove the backdrop?

I also found this issue on SpinKit, and I tried the jsFiddle that is inside this [issue](https://github.com/tobiasahlin/SpinKit/issues/127) and that doesn't add any backdrop and I'm able to click on a button (after adding one in that demo).

**Comment by mpalourdio** [comment]
Mmmhh, I don't know if playing with z-index could do the trick. Something like that would make the background clickable.

```css
#spinner {
  z-index: -1; !important;
}
```

**Comment by ghiscoding** [comment]
oh wow I tried removing the `z-index` before and that didn't work but your solution does work. You're the man 👍 

BTW there's a typo in your code, there's no `;` after `-1`

Thanks a lot, that makes my day 😃 
I can close the ticket woohoo

**Comment by mpalourdio** [comment]
I have tried with

```css
#spinner {
    height: 30%;
    width: 30%;
    z-index: 0;
    ```

This makes the spinner appear in any situation. (You will have to tweak the position though)

**Comment by mpalourdio** [comment]
> oh wow I tried removing the `z-index` before and that didn't work but your solution does work. You're the man +1

Cool !
> BTW there's a typo in your code, there's no `;` after `-1`

Edited !

> Thanks a lot, that makes my day smiley
> I can close the ticket woohoo

**Comment by ghiscoding** [comment]
I tried with `z-index: 0` and that doesn't work, however `z-index: -1` does the trick. This might be interesting to have as a configuration for your spinner, something like `backdrop: false` but I'm more than happy with just overriding the z-index myself

**Comment by mpalourdio** [comment]
Weird because I have tried with `z-index: 0` and it works. `z-index: -1` could make the spinner hidden by other HTML on your page. That's more a hack than a fix.

Noting your suggestion for a further patch :)

**Comment by ghiscoding** [comment]
I'm also using Chrome and only -1 works, so I'll stay with that. If you do create a new config for it, then might as well add a SASS variable for it, so that user could use 0 or -1 depending on their need. 

Thanks for the fast answer and awesome library. 
Cheers :)

**Comment by mpalourdio** [comment]
OK, that's strange.

Out of curiosity, how would one use a SASS variable once the module in packaged an a node_modules ? During the build process, the scss is 'compiled' to css. Have you got an example ?

**Comment by ghiscoding** [comment]
I use SASS for my lib, you can see all my SASS variables [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/styles/_variables.scss) and the instructions on how to use them in your project is in this [wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Styling). The only thing to remember is to add `!default;` at the end of each variables which allows them to be override. So anyone using my lib can choose the compiled CSS or SASS. 

Does that answer your question?

**Comment by mpalourdio** [comment]
Thanks, looks interesting !

**Comment by ghiscoding** [comment]
Seems I've talked too fast, it was working only on first load. At the end `-1` doesn't work and `0` is still over some of my elements. I tried resizing the `#spinner` to fixed width and height to `50px` but then as you said I now have position problems. 

I'll put this one aside for now, it would be nice to get it without backdrop but I already spent too much time on this. I just wonder if I should leave the issue opened in case someone else has better solution?

**Comment by mpalourdio** [comment]
Yes, the backdrop is by design, not really sure how to provide such a configurable option. My CSS skills are really poor :D

**Comment by ghiscoding** [comment]
I'm reopening this issue because I really had to fix, that is to remove backdrop (not being able to click anything in the background was a major issue for our application). The good news is that I found the CSS needed for it to work. I'd like to know if it would be possible to improve your lib and possibly export the SASS configuration so that we could (user of your lib) could change it through SASS

Here's the code that removes the backdrop (also note that I need to use `!important` everywhere). If I could override these properties through SASS that would make it more flexible, or if you have another suggestion to do it by code that would also work for me

```sass
/* HTTP Request Spinner */
$spinner-height: 50px;
$spinner-width: 50px;

#spinner {
  opacity: 0.4 !important;
  position: absolute !important;
  height: $spinner-height !important;
  width: $spinner-width !important;
  top: 50% !important;
  left: 50% !important;
}
.sk-double-bounce {
  width: $spinner-height !important;
  height: $spinner-width !important;
}
```

**Comment by mpalourdio** [comment]
Thanks for feedback. Last time I was thinking of including a way to override CSS by SASS at userland, I was not really convinced. 
The main reason is that it would force the user, even the one that does not want to override settings, to include a stylesheet in his application.

What is cool at the moment, it's that the module is 'plug & play', without too much configuration to be up and running.

Anyway, for the moment, even if 'dirty', CSS overriding does the trick. I need more time to take a look at that.

**Comment by ghiscoding** [comment]
No problem, I actually have another idea after sleeping over it. You could add a `backdrop` class and provide an option to the user to disable it or not. That would be easier to the user and also nice to provide an extra configuration.

I did not test anything, but I thing that would work going this route

#### Usage
```ts
<ng-http-loader 
    [backgroundColor]="'#ff0000'"
    [spinner]="spinkit.skWave"
    [backdrop]="true">
</ng-http-loader>
```

#### Lib Component (ng-http-loader.component.html)
```html
<div id="spinner" [ngClass]="useBackdrop ? 'backdrop' : ''" *ngIf="isVisible$ | async">
```

```sass
#spinner {
    top: 0;
    left: 0;
    height: 100%;
    width: 100%;
    position: fixed;
    z-index: 9999;
    display: flex;
    align-items: center;
    justify-content: center;
    opacity: $spinner-opacity;
    background-color: $spinner-background-color;

  .backdrop {
    position: absolute !important;
    height: $spinkit-size;
    width: $spinkit-size;
    top: 50%;
    left: 50%;
}
```

I'm not sure if we need `!important` in any of the `.backdrop` properties.

**Comment by mpalourdio** [comment]
Thanks, I much prefer this approach but AFAICT, that won't fix the problem because we need a way to manually provide `$spinkit-size`.

**Comment by mpalourdio** [comment]
I have just tested this, without the need to set `height` and `width` when there is no `backdrop`. WDYT about it ? Would it do the trick ?

```css
@import "variables";

#spinner {
    top: 50%;
    left: 50%;
    position: absolute;
    z-index: 9999;
    display: flex;
    align-items: center;
    justify-content: center;
    opacity: $spinner-opacity;
    background-color: $spinner-background-color;

    &.backdrop {
        top: 0;
        left: 0;
        height: 100% ;
        width: 100% ;
        position: fixed;
    }
}


::ng-deep .colored-parent, ::ng-deep .colored > div {
    background-color: $colored-background-color;
}
```

**Comment by ghiscoding** [comment]
Ah cool, I didn't know the background could be removed, I had the impression that the spinner wasn't going to show without a background color. That is even better then :)

I would be very interested to try it out

**Comment by mpalourdio** [comment]
The background removed here is the background of the backdrop. I'm still tweaking the CSS, all I can say if that I am really n00b at positioning things :D

The `backdrop` term seems weird to me. Not sure if we should keep this name for the `@Input()`. To keep BC, the backdropt should stille be there by default.

I might release a first beta tomorrow hopefully.

**Comment by ghiscoding** [comment]
Yeah I totally understand that, I'm also not an expert in CSS, Google is my friend lol. As for the term backdrop, that is the word they use with [Bootstrap Modal](https://getbootstrap.com/docs/4.3/components/modal/) window, you can view a demo on [ngx-bootstrap model](https://valor-software.com/ngx-bootstrap/#/modals#service-disable-backdrop), on that demo if you can click on "disable backdrop", it removes the blurry background which to me is exactly what your spinner does hence why that name.

**Comment by mpalourdio** [comment]
Yes, exactly my conclusion regarding how CSS frameworks name this. I have made a PR with this feature in #114

**Comment by ghiscoding** [comment]
Yes I saw, I just left a comment to add 1 word in the description. Your code is really nice, really good job :)

**Comment by mpalourdio** [comment]
@ghiscoding Just published 5.1.0-beta.0, please give it a try.

**Comment by ghiscoding** [comment]
I'll try it out on Monday, thanks a lot

**Comment by ghiscoding** [comment]
@mpalourdio 
I tried the Beta 0 version, it's working fine and simplifies my code a lot. 
Just a side note though, I still have to override some of the CSS properties with `!important`, if you could add these properties as well with new variables that would be super awesome, but I can live with the `!important` too. I'll let you decide.

Here's the remaining variables I still override with `!important` because they are not exposed in your lib.
I think the 2nd one, you can't do much about it since it's in every single type of spinner, however the opacity you might be able to expose a new variable. 

```css
#spinner {
  opacity: 0.45 !important;
}

.sk-double-bounce {
  width: 55px !important;
  height: 55px !important;
}
```

**Comment by mpalourdio** [comment]
I'm ok that opacity could be configurable. Regarding height and width, this will be very cumbersome because there's a lot of spinner, and I think that it most cases, size is ok. Anyway, you can configure height and width by refining your CSS selector

```css
::ng-deep #spinner .sk-wave {
    height: 55px;
    width:55px
}
```

**Comment by mpalourdio** [comment]
I just pushed `5.1.0-beta.1` with the possibility to override the `opacity`.

**Comment by ghiscoding** [comment]
This version will be super sweet for me, I just tried the opacity and it's great 👍  
You have my blessing for the new version, thanks for all new features, love it 😃 

Side note, the only thing that doesn't work, which is outside of the PR, is the code you provided for the spinner size. I'm not sure if it's because I use a different spinner than the one you said.

```css
/* doesn't work, with or without !important also doesn't make a difference */
::ng-deep #spinner .sk-double-bounce {
  width: 100px;
  height: 100px;
}

/* only this works with !important */
.sk-double-bounce {
  width: 100px !important;
  height: 100px !important;
}
```
